services:
  - type: web
    name: nokertin-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: static_site
    name: nokertin-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://nokertin-backend.onrender.com
