services:
  - type: web
    name: nokertinki-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: static_site
    name: nokertinki-frontend
    rootDir: .
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://nokertinki-advanced1.onrender.com
